import enum


class GrantType(enum.StrEnum):
    PASSWORD = "PASSWORD"
    REFRESH_TOKEN = "REFRESH_TOKEN"


class TaskType(enum.StrEnum):
    JOIN_CHAT = "JOIN_CHAT"
    EXPORT_CHAT_MEMBERS = "EXPORT_CHAT_MEMBERS"
    TERMLY_READ_MESSAGES = "TERMLY_READ_MESSAGES"
    READ_MESSAGE = "READ_MESSAGE"
    REACT_MESSAGE = "REACT_MESSAGE"
    COMMENT_MESSAGE = "COMMENT_MESSAGE"


class TaskStatus(enum.StrEnum):
    CREATED = "CREATED"
    PENDING = "PENDING"
    PAUSING = "PAUSING"
    NOT_COMPLETED = "NOT_COMPLETED"
    ILLEGAL = "ILLEGAL"
    INVALID = "INVALID"
    COMPLETED = "COMPLETED"
